version: '3'
services:
  keycloak_db:
    image: postgres:11.2-alpine
    environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_ROOT_PASSWORD=${POSTGRES_ROOT_PASSWORD}
    volumes:
      - keycloak_db_vol:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak
    environment:
      - DB_VENDOR=${DB_VENDOR}
      - DB_ADDR=${DB_ADDR}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_SCHEMA=${DB_SCHEMA}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - PROXY_ADDRESS_FORWARDING=${PROXY_ADDRESS_FORWARDING}
      - KEYCLOAK_LOGLEVEL=${KEYCLOAK_LOGLEVEL}
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
      - KEYCLOAK_IMPORT=/tmp/keycloak/realm.json
    depends_on: 
      - keycloak_db
    volumes:
      - ./keycloak/realm.json:/tmp/keycloak/realm.json

  service_app:
    image: php:7.1.2-apache
    restart: always
    env_file: 
      - .env
    working_dir: /var/www/html/
    volumes: 
      - ./service/php:/var/www/html/

  nginx:
    image: nginx
    ports:
      - 80:80
    depends_on:
      - service_app
      - keycloak
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

volumes: 
  keycloak_db_vol:
